# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from email_send_grpc import emailService_pb2 as emailService__pb2


class email_serviceStub(object):
    """The user service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendEmail = channel.unary_unary(
                '/email.email_service/sendEmail',
                request_serializer=emailService__pb2.sendEmailDetails.SerializeToString,
                response_deserializer=emailService__pb2.response.FromString,
                )


class email_serviceServicer(object):
    """The user service definition.
    """

    def sendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_email_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.sendEmail,
                    request_deserializer=emailService__pb2.sendEmailDetails.FromString,
                    response_serializer=emailService__pb2.response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'email.email_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class email_service(object):
    """The user service definition.
    """

    @staticmethod
    def sendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/email.email_service/sendEmail',
            emailService__pb2.sendEmailDetails.SerializeToString,
            emailService__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
