# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emailService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='emailService.proto',
  package='email',
  syntax='proto3',
  serialized_options=b'\n\026io.grpc.examples.emailB\005emailP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x65mailService.proto\x12\x05\x65mail\"\xbc\x01\n\x10sendEmailDetails\x12\x14\n\x0c\x65mailService\x18\x01 \x01(\t\x12\x0f\n\x07toEmail\x18\x02 \x01(\t\x12\x10\n\x08userName\x18\x03 \x01(\t\x12\x0f\n\x07subject\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\x12\x0f\n\x07trigger\x18\x06 \x01(\t\x12\x14\n\x0chttpFilePath\x18\x07 \x01(\t\x12\x15\n\rlocalFilePath\x18\x08 \x01(\t\x12\x12\n\ncampaignId\x18\t \x01(\t\"\x1b\n\x08response\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\remail_service\x12\x37\n\tsendEmail\x12\x17.email.sendEmailDetails\x1a\x0f.email.response\"\x00\x42\'\n\x16io.grpc.examples.emailB\x05\x65mailP\x01\xa2\x02\x03HLWb\x06proto3'
)




_SENDEMAILDETAILS = _descriptor.Descriptor(
  name='sendEmailDetails',
  full_name='email.sendEmailDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='emailService', full_name='email.sendEmailDetails.emailService', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='toEmail', full_name='email.sendEmailDetails.toEmail', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userName', full_name='email.sendEmailDetails.userName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject', full_name='email.sendEmailDetails.subject', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='email.sendEmailDetails.body', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trigger', full_name='email.sendEmailDetails.trigger', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='httpFilePath', full_name='email.sendEmailDetails.httpFilePath', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='localFilePath', full_name='email.sendEmailDetails.localFilePath', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='campaignId', full_name='email.sendEmailDetails.campaignId', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=218,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='email.response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='email.response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=247,
)

DESCRIPTOR.message_types_by_name['sendEmailDetails'] = _SENDEMAILDETAILS
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

sendEmailDetails = _reflection.GeneratedProtocolMessageType('sendEmailDetails', (_message.Message,), {
  'DESCRIPTOR' : _SENDEMAILDETAILS,
  '__module__' : 'emailService_pb2'
  # @@protoc_insertion_point(class_scope:email.sendEmailDetails)
  })
_sym_db.RegisterMessage(sendEmailDetails)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'emailService_pb2'
  # @@protoc_insertion_point(class_scope:email.response)
  })
_sym_db.RegisterMessage(response)


DESCRIPTOR._options = None

_EMAIL_SERVICE = _descriptor.ServiceDescriptor(
  name='email_service',
  full_name='email.email_service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=249,
  serialized_end=321,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendEmail',
    full_name='email.email_service.sendEmail',
    index=0,
    containing_service=None,
    input_type=_SENDEMAILDETAILS,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMAIL_SERVICE)

DESCRIPTOR.services_by_name['email_service'] = _EMAIL_SERVICE

# @@protoc_insertion_point(module_scope)
