# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_validation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inventory_validation.proto',
  package='inventory',
  syntax='proto3',
  serialized_options=b'\n\032io.grpc.examples.inventoryB\tinventoryP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ainventory_validation.proto\x12\tinventory\"%\n\x10InventoryRequest\x12\x11\n\tbody_data\x18\x01 \x01(\t\"!\n\x0eInventoryReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\\\n\x07Greeter\x12Q\n\x15ValidateInventoryData\x12\x1b.inventory.InventoryRequest\x1a\x19.inventory.InventoryReply\"\x00\x42/\n\x1aio.grpc.examples.inventoryB\tinventoryP\x01\xa2\x02\x03HLWb\x06proto3'
)




_INVENTORYREQUEST = _descriptor.Descriptor(
  name='InventoryRequest',
  full_name='inventory.InventoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='body_data', full_name='inventory.InventoryRequest.body_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=78,
)


_INVENTORYREPLY = _descriptor.Descriptor(
  name='InventoryReply',
  full_name='inventory.InventoryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='inventory.InventoryReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['InventoryRequest'] = _INVENTORYREQUEST
DESCRIPTOR.message_types_by_name['InventoryReply'] = _INVENTORYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InventoryRequest = _reflection.GeneratedProtocolMessageType('InventoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVENTORYREQUEST,
  '__module__' : 'inventory_validation_pb2'
  # @@protoc_insertion_point(class_scope:inventory.InventoryRequest)
  })
_sym_db.RegisterMessage(InventoryRequest)

InventoryReply = _reflection.GeneratedProtocolMessageType('InventoryReply', (_message.Message,), {
  'DESCRIPTOR' : _INVENTORYREPLY,
  '__module__' : 'inventory_validation_pb2'
  # @@protoc_insertion_point(class_scope:inventory.InventoryReply)
  })
_sym_db.RegisterMessage(InventoryReply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='inventory.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=115,
  serialized_end=207,
  methods=[
  _descriptor.MethodDescriptor(
    name='ValidateInventoryData',
    full_name='inventory.Greeter.ValidateInventoryData',
    index=0,
    containing_service=None,
    input_type=_INVENTORYREQUEST,
    output_type=_INVENTORYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
